name: Send Crossword Link

on:
  schedule:
    - cron: "30 18 * * *" # Currently set to 11:30am PST, however on exuction it will run around 12-12:30pm which is the target time (UTC-7/8, adjust seasonally)
    - cron: "30 22 * * *" # 3:30pm PST target, 30m-1h offset
  workflow_dispatch: # lets you trigger manually from the Actions tab for testing

jobs:
  send-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Ensure browser installed
        run: playwright install --with-deps chromium

      - name: Run crossword bot
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: python send_crossword.py
